### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by Lightczx** [TremblingMoeNew/DodocoTales#1]
1. 应用程序任务栏标题没改
2. `GlassFrameThickness="1"` 导致边框有一条难看的白线
```xaml
<WindowChrome CaptionHeight="30" GlassFrameThickness="1" UseAeroCaptionButtons="False" NonClientFrameEdges="None"/>
```
3. 后退按钮无实际功能
4. 设置按钮无实际功能
5. 下抽概率总是为 ——/——/——
6. 分段式的进度条无各颜色意义说明，很难明白颜色对应的星级
7. 进度条的提示有严重的刷新显示问题，可读性很差
7. 没有记录导出功能
8. 卡池内排版不太清晰，可能完全左对齐会好一点，不太需要不必要的缩进
9. 左侧导航栏的排版也不太好，完全可以左对齐
10. 某些情况下统计的2个子项无法点击
10. 获取记录时未使用异步方法，会锁死UI

**Comment by Lightczx** [comment]
虽然设置了最低宽度，但是没有设置最低高度

**Comment by TremblingMoeNew** [comment]
1. Get
2. Get，不过不是因为这行，是因为下面的样式里设了1的Margin；现在它是一条灰色边框线了；
3. 其实是有用的，但是点左侧菜单栏的按钮时会把页面栈弹空、即“首页”、“统计/按照版本”、“统计/按照类型”三个页面永远在栈底，在这三个页面点返回确实没啥用……目前只有从“统计”的两个子页面里、点击卡池信息进入卡池详情页面后，点返回才有用，因为只有卡池详情页面不是一级页面
4. 设置页面还没做呢（
5. 在做了再做了

> ### 未来……
> - 借助概率经验模型，为您提供更多的信息。

6. 我不知道该怎么解释……那个进度条的四种颜色分别代表在当前的大保底之中：你在过往的池子里抽到歪抽了多少抽（紫色）；你这轮小保底里多少抽是在过往池子里抽的（灰色）；你在当前池子里抽到歪又追加抽了多少抽（玫红色）；以及，你当前池子里这轮小保底抽了多少抽（蓝色）……这解释起来都这么费劲我实在不知道怎么写图例了.jpg
7. 是一直在闪烁吗？我在想办法……
8. get，以后会考虑添加这个功能

11.具体是在什么情况下会出现，能详细描述一下吗
12.其实是异步获取的来着的，但是那个弹出的加载提示是个模态对话框……

**Comment by Lightczx** [comment]
没做完的功能就先visibility设成hidden或者collasped吧
11的情况有些难复现，但是就是会出现某些页签无法点击的情况，在点击其他页签后才能正常点击
12那就别弹模态框了，窗体顶部加个无终点进度条/或者win10的进度环之类的好一点，ui不能交互就会感觉程序的性能很差

**Comment by Lightczx** [comment]
6的进度条也搞个tooltip不就行了？
